#!/bin/python

import datetime

now = datetime.datetime.now()
launch = datetime.datetime(2021, 12, 25, 13, 20)

delta = launch-now
delta -= datetime.timedelta(microseconds=delta.microseconds)

print(delta)
